### ISSUE TITLE
Error with hapi ^9.1.0

### ISSUE THREAD

**Issue by mandado** [gergoerdosi/hapi-json-view#19]
When run sudo npm install --save hapi-json-view, I got this error:
 
error peerinvalid The package hapi does not satisfy its siblings' peerDependencies requirements!
error peerinvalid Peer hapi-json-view@2.1.0 wants hapi@8.x.x.

Is a package problem or how solve this ??

Thanks.

**Comment by gergoerdosi** [comment]
Released v3.0.0 which is compatible with hapi 9.x.x.
